name: Clang build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        branch: [main, release/16.x]

    env:
      BRANCH: ${{ matrix.branch }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: build ${{ matrix.branch }} branch
        run: |
          git clone -b master https://github.com/XSans0/clang-build
          cd clang-build || exit
          bash ci.sh deps
          bash build.sh