name: Clang build test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      LLVM_BRANCH: main
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Building
        run: |
          git clone -b rebase https://github.com/XSans0/clang-build
          cd clang-build || exit
          bash ci.sh deps
          bash build.sh
